version: '3'

services:
  reverse-proxy:
    restart: always
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    hostname: reverse-proxy
    command: --api.insecure=true --providers.docker --entrypoints.web.address=:80
        #- --entrypoints.web-secure.address=:443 #Declares the web-secure entrypoint in Traefik
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

#  public-api:
#    restart: always
#    build:
#      context: ./public_api/img/
#      dockerfile: Dockerfile
#    hostname: ${PUBLIC_API_HOST}
#    command: uvicorn --host "0.0.0.0" --port ${PUBLIC_API_PORT} api:app
#    env_file:
#      - .env
#    ports:
#      - ${PUBLIC_API_PORT}:${PUBLIC_API_PORT}
#    labels:
#      - "traefik.http.routers.${PUBLIC_API_HOST}.rule=Host(`localhost`)"
#      - "traefik.http.services.${PUBLIC_API_HOST}.loadbalancer.server.port=${PUBLIC_API_PORT}"
#    volumes:
#      - ${DATA_VOLUME}:/data


  database:
    image: postgres:latest
    restart: always
    hostname: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    #volumes:
    #  - ${DB_VOLUME}:/var/lib/postgresql/data

  api:
    hostname: ${API_HOST}
    command: uvicorn --host "0.0.0.0" --port ${API_PORT} api:app
    depends_on:
      - rabbit
    ports:
      - ${API_PORT}:${API_PORT}
    labels:
      - "traefik.http.routers.${API_HOST}.rule=Host(`localhost`)"
      - "traefik.http.services.${API_HOST}.loadbalancer.server.port=${API_PORT}"
    env_file:
      - .env
    build:
      context: private_api/img/
      dockerfile: Dockerfile
    volumes:
      - ${DATA_VOLUME}:/data

  rabbit:
    restart: always
    image: rabbitmq:latest
    ports:
      - 5672:5672
    hostname: rabbit

  job-consumer:
    hostname: job_consumer
    depends_on:
      - rabbit
      - api
    env_file:
      - .env
    build:
      context: ./job_consumer/img
      dockerfile: Dockerfile
    #ipc: host
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [ gpu ]
    volumes:
      ## needed to run docker in docker with GPU-support
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db_storage:
  data_storage:

